In [3]:
import pandas as pd
import numpy as np
import math
import pickle
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [4]:
# the information of stocks(i.e. name & category of sector).
SP500_name = pd.read_csv("./datasets4/arrange_sp500_companies.csv", encoding='ISO-8859-1')
# SP500_stock_df = pd.read_csv("../datasets/sp500_stocks.csv")
# SP500_name.head()

# original information of stock price.
SP500_stock = {}
for target in SP500_name["Symbol"].unique():
    da = {}
    da["category"] = SP500_name[SP500_name.Symbol == target]["Sector"].iloc[0]
    da["stock_price"] = pd.read_csv("./SP500_dataset/%s.csv"%(target), encoding='ISO-8859-1')
    SP500_stock[target] = da

In [12]:
SP500_stock['AAPL']['stock_price']

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-01-02,27.847500,27.860001,26.837500,27.332500,24.466448,212818400
1,2015-01-05,27.072500,27.162500,26.352501,26.562500,23.777191,257142000
2,2015-01-06,26.635000,26.857500,26.157499,26.565001,23.779428,263188400
3,2015-01-07,26.799999,27.049999,26.674999,26.937500,24.112862,160423600
4,2015-01-08,27.307501,28.037500,27.174999,27.972500,25.039337,237458000
...,...,...,...,...,...,...,...
2009,2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900
2010,2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800
2011,2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339417,85438400
2012,2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700
2013,2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207794,77034200

In [13]:
# Let all stocks has the same date.
print(SP500_stock.keys())
need_day = np.array(SP500_stock["AAPL"]["stock_price"]["Date"])
for target in SP500_stock.keys():
    SP500_stock[target]["stock_price"] = SP500_stock[target]["stock_price"][SP500_stock[target]["stock_price"]["Date"].isin(need_day)].reset_index(
        drop=True
    )
    SP500_stock[target]["stock_price"].index = SP500_stock[target]["stock_price"]["Date"]
print('same date over')

dict_keys(['LVS', 'NWS', 'NWSA', 'LYV', 'DIS', 'ROL', 'CMG', 'MGM', 'CTAS', 'HLT', 'SBUX', 'CMCSA', 'DPZ', 'BKNG', 'YUM', 'MCD', 'MAR', 'DRI', 'EXPE', 'CZR', 'CHTR', 'WBD', 'RCL', 'CCL', 'WYNN', 'PARA', 'CRM', 'PANW', 'TYL', 'CSGP', 'NOW', 'VRSK', 'CDNS', 'IBM', 'SNPS', 'INTU', 'PTC', 'ADSK', 'PAYC', 'FICO', 'ANSS', 'ADBE', 'MSCI', 'NFLX', 'FTNT', 'ROP', 'TRMB', 'ORCL', 'EA', 'AKAM', 'BR', 'ATVI', 'META', 'FDS', 'MSFT', 'JKHY', 'ADP', 'VRSN', 'IT', 'FFIV', 'PAYX', 'MTCH', 'GOOG', 'ACN', 'GOOGL', 'EPAM', 'CDW', 'J', 'JNPR', 'CSCO', 'CTSH', 'GEN', 'FIS', 'TTWO', 'TAP', 'CLX', 'VFC', 'TSN', 'EL', 'CHD', 'MNST', 'BF-B', 'CL', 'MKC', 'NKE', 'PEP', 'KDP', 'KMB', 'PG', 'KO', 'HSY', 'K', 'MDLZ', 'HRL', 'CAG', 'PM', 'CPB', 'GIS', 'RL', 'MO', 'STZ', 'IFF', 'SJM', 'WELL', 'VTR', 'DLR', 'EQIX', 'AMT', 'CPT', 'SBAC', 'PGR', 'IRM', 'AJG', 'O', 'ICE', 'MKTX', 'ARE', 'WY', 'PLD', 'KIM', 'CBRE', 'PRU', 'FI', 'EQR', 'MMC', 'ESS', 'UDR', 'REG', 'MAA', 'BRO', 'CCI', 'AON', 'CME', 'CBOE', 'MET', 'NDAQ', 'AIZ', 'PEAK', 'EXR', 'FRT', 'AVB', 'WTW', 'BLK', 'SPG', 'SCHW', 'TRV', 'BEN', 'AXP', 'TROW', 'AMP', 'HST', 'BXP', 'MS', 'CB', 'GS', 'NTRS', 'URI', 'WRB', 'RJF', 'GL', 'BK', 'ACGL', 'CINF', 'PSA', 'PFG', 'L', 'EG', 'HIG', 'IVZ', 'WFC', 'USB', 'AFL', 'AIG', 'JPM', 'STT', 'BRK-B', 'PNC', 'BAC', 'RF', 'COF', 'MTB', 'FITB', 'KEY', 'HBAN', 'C', 'TFC', 'DFS', 'CFG', 'SYF', 'ZION', 'CMA', 'ALL', 'PODD', 'CTLT', 'STE', 'DXCM', 'MRK', 'ALGN', 'LLY', 'ISRG', 'COO', 'WST', 'IDXX', 'ZBH', 'BDX', 'TECH', 'INCY', 'SYK', 'ZTS', 'HOLX', 'TMO', 'ABT', 'JNJ', 'EW', 'A', 'ABBV', 'MTD', 'DHR', 'MDT', 'TFX', 'RMD', 'VRTX', 'WAT', 'REGN', 'AMGN', 'RVTY', 'GILD', 'BMY', 'BIIB', 'PFE', 'VTRS', 'ILMN', 'WBA', 'BAX', 'BIO', 'XRAY', 'NVDA', 'AXON', 'FSLR', 'MPWR', 'TDG', 'GLW', 'LHX', 'ANET', 'ENPH', 'MSI', 'TER', 'AAPL', 'APH', 'AVGO', 'TDY', 'ADI', 'ROK', 'HON', 'RTX', 'ZBRA', 'ON', 'KEYS', 'TXN', 'KLAC', 'TEL', 'GRMN', 'LDOS', 'NXPI', 'GD', 'MCHP', 'TXT', 'HII', 'LMT', 'SWKS', 'QCOM', 'NOC', 'NTAP', 'HPQ', 'AMD', 'INTC', 'BA', 'MU', 'EMR', 'STX', 'WDC', 'QRVO', 'AMZN', 'COST', 'WMT', 'CVS', 'KMX', 'TJX', 'ORLY', 'ROST', 'DLTR', 'TSCO', 'LOW', 'HD', 'AZO', 'ULTA', 'TGT', 'EBAY', 'DG', 'KR', 'BBY', 'BBWI', 'AAP', 'TPR', 'CAH', 'BSX', 'FAST', 'POOL', 'HSIC', 'COR', 'GWW', 'GPC', 'MCK', 'TSLA', 'SWK', 'SNA', 'LKQ', 'NVR', 'F', 'DHI', 'LEN', 'PHM', 'GM', 'HAS', 'WHR', 'XYL', 'GNRC', 'AOS', 'ETN', 'WAB', 'APTV', 'AME', 'IEX', 'NDSN', 'PH', 'TT', 'ITW', 'PNR', 'JCI', 'LRCX', 'DOV', 'AMAT', 'ALLE', 'CAT', 'MAS', 'GE', 'CMI', 'PCAR', 'DE', 'BWA', 'MMM', 'SPGI', 'EFX', 'MCO', 'GPN', 'MA', 'CPRT', 'V', 'FLT', 'CRL', 'RHI', 'IPG', 'OMC', 'PWR', 'BKR', 'RSG', 'WM', 'SLB', 'WMB', 'KMI', 'HAL', 'OKE', 'DUK', 'FE', 'AWK', 'EIX', 'PPL', 'CNP', 'SO', 'TRGP', 'CMS', 'PNW', 'AEP', 'WEC', 'ATO', 'LNT', 'ES', 'AEE', 'EXC', 'XEL', 'NI', 'PCG', 'D', 'SRE', 'EVRG', 'NEE', 'DTE', 'ETR', 'ED', 'PEG', 'AES', 'NRG', 'ECL', 'LIN', 'SHW', 'APD', 'AVY', 'PPG', 'BALL', 'FMC', 'PKG', 'LYB', 'EMN', 'AMCR', 'SEE', 'ADM', 'CE', 'BG', 'IP', 'DD', 'CF', 'MOS', 'ALB', 'VMC', 'MLM', 'FCX', 'NUE', 'STLD', 'NEM', 'LUV', 'ALK', 'ODFL', 'JBHT', 'CHRW', 'SYY', 'UNP', 'NSC', 'EXPD', 'FDX', 'CSX', 'UPS', 'DAL', 'UAL', 'AAL', 'IQV', 'LH', 'UNH', 'DVA', 'MOH', 'DGX', 'HUM', 'ELV', 'UHS', 'HCA', 'CNC', 'CI', 'HES', 'COP', 'OXY', 'CVX', 'PXD', 'APA', 'EOG', 'XOM', 'MRO', 'FANG', 'CTRA', 'DVN', 'MPC', 'PSX', 'EQT', 'VLO', 'TMUS', 'VZ', 'T'])
same date over

In [14]:
SP500_stock['AAPL']['stock_price']

,Date,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2015-01-02,2015-01-02,27.847500,27.860001,26.837500,27.332500,24.466448,212818400
2015-01-05,2015-01-05,27.072500,27.162500,26.352501,26.562500,23.777191,257142000
2015-01-06,2015-01-06,26.635000,26.857500,26.157499,26.565001,23.779428,263188400
2015-01-07,2015-01-07,26.799999,27.049999,26.674999,26.937500,24.112862,160423600
2015-01-08,2015-01-08,27.307501,28.037500,27.174999,27.972500,25.039337,237458000
...,...,...,...,...,...,...,...
2022-12-23,2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900
2022-12-27,2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800
2022-12-28,2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339417,85438400
2022-12-29,2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700
2022-12-30,2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207794,77034200

In [15]:
# normalize stock price
normalize_scalar = {}
for target in SP500_stock.keys():
    scaler = StandardScaler()
    nor_data = scaler.fit_transform(np.array(SP500_stock[target]["stock_price"]["Close"]).reshape(-1, 1)).ravel()
    SP500_stock[target]["stock_price"]["nor_close"] = nor_data
    normalize_scalar[target] = scaler

print('normalize over')

normalize over

In [16]:
SP500_stock['AAPL']['stock_price']

,Date,Open,High,Low,Close,Adj Close,Volume,nor_close
Date,,,,,,,,
2015-01-02,2015-01-02,27.847500,27.860001,26.837500,27.332500,24.466448,212818400,-0.933450
2015-01-05,2015-01-05,27.072500,27.162500,26.352501,26.562500,23.777191,257142000,-0.949176
2015-01-06,2015-01-06,26.635000,26.857500,26.157499,26.565001,23.779428,263188400,-0.949125
2015-01-07,2015-01-07,26.799999,27.049999,26.674999,26.937500,24.112862,160423600,-0.941517
2015-01-08,2015-01-08,27.307501,28.037500,27.174999,27.972500,25.039337,237458000,-0.920379
...,...,...,...,...,...,...,...,...
2022-12-23,2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900,1.201329
2022-12-27,2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800,1.163954
2022-12-28,2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339417,85438400,1.082466
2022-12-29,2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700,1.155377
2022-12-30,2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207794,77034200,1.161912

In [17]:
# calculate return ratio
for target in SP500_stock.keys():
    return_tratio = []
    data = np.array(SP500_stock[target]["stock_price"]["Close"])
    for i in range(len(data)):
        if i == 0:
            return_tratio.append(0)
        else:
            return_tratio.append((data[i] - data[i - 1]) / data[i - 1])
    SP500_stock[target]["stock_price"]["return ratio"] = return_tratio
print('calculate return ratio over')

calculate return ratio over

In [18]:
SP500_stock['AAPL']['stock_price']

,Date,Open,High,Low,Close,Adj Close,Volume,nor_close,return ratio
Date,,,,,,,,,
2015-01-02,2015-01-02,27.847500,27.860001,26.837500,27.332500,24.466448,212818400,-0.933450,0.000000
2015-01-05,2015-01-05,27.072500,27.162500,26.352501,26.562500,23.777191,257142000,-0.949176,-0.028172
2015-01-06,2015-01-06,26.635000,26.857500,26.157499,26.565001,23.779428,263188400,-0.949125,0.000094
2015-01-07,2015-01-07,26.799999,27.049999,26.674999,26.937500,24.112862,160423600,-0.941517,0.014022
2015-01-08,2015-01-08,27.307501,28.037500,27.174999,27.972500,25.039337,237458000,-0.920379,0.038422
...,...,...,...,...,...,...,...,...,...
2022-12-23,2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900,1.201329,-0.002798
2022-12-27,2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800,1.163954,-0.013878
2022-12-28,2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339417,85438400,1.082466,-0.030685
2022-12-29,2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700,1.155377,0.028324
2022-12-30,2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207794,77034200,1.161912,0.002469

In [19]:
# feature of c_open / c_close / c_low
for target in SP500_stock.keys():
    function = lambda x, y: (x / y) - 1
    data = SP500_stock[target]["stock_price"]
    data["c_open"] = list(map(function, data["Open"], data["Close"]))
    data["c_high"] = list(map(function, data["High"], data["Close"]))
    data["c_low"] = list(map(function, data["Low"], data["Close"]))
print('calculate c_feature over')

calculate c_feature over

In [20]:
SP500_stock['AAPL']['stock_price']

,Date,Open,High,Low,Close,Adj Close,Volume,nor_close,return ratio,c_open,c_high,c_low
Date,,,,,,,,,,,,
2015-01-02,2015-01-02,27.847500,27.860001,26.837500,27.332500,24.466448,212818400,-0.933450,0.000000,0.018842,0.019299,-0.018110
2015-01-05,2015-01-05,27.072500,27.162500,26.352501,26.562500,23.777191,257142000,-0.949176,-0.028172,0.019200,0.022588,-0.007906
2015-01-06,2015-01-06,26.635000,26.857500,26.157499,26.565001,23.779428,263188400,-0.949125,0.000094,0.002635,0.011011,-0.015340
2015-01-07,2015-01-07,26.799999,27.049999,26.674999,26.937500,24.112862,160423600,-0.941517,0.014022,-0.005104,0.004176,-0.009745
2015-01-08,2015-01-08,27.307501,28.037500,27.174999,27.972500,25.039337,237458000,-0.920379,0.038422,-0.023773,0.002324,-0.028510
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900,1.201329,-0.002798,-0.007129,0.004247,-0.016836
2022-12-27,2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800,1.163954,-0.013878,0.010382,0.010613,-0.010075
2022-12-28,2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339417,85438400,1.082466,-0.030685,0.028800,0.039591,-0.001349
2022-12-29,2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700,1.155377,0.028324,-0.012499,0.006712,-0.014505
2022-12-30,2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207794,77034200,1.161912,0.002469,-0.011699,0.000154,-0.019241

In [21]:
# 5 / 10 / 15 / 20 / 25 / 30 days moving average
for target in SP500_stock.keys():
    data = SP500_stock[target]["stock_price"]["Close"]
    for i in [5, 10, 15, 20, 25, 30]:
        q = []
        for day in range(len(data)):
            if day >= i - 1:
                q.append((np.mean(data.iloc[day - i + 1 : day + 1]) / data.iloc[day]) - 1)
            if day < i - 1:
                q.append(0)
        SP500_stock[target]["stock_price"]["%s-days" % (i)] = q
print('calculate moving average over')

calculate moving average over

In [22]:
SP500_stock['AAPL']['stock_price']

,Date,Open,High,Low,Close,Adj Close,Volume,nor_close,return ratio,c_open,c_high,c_low,5-days,10-days,15-days,20-days,25-days,30-days
Date,,,,,,,,,,,,,,,,,,
2015-01-02,2015-01-02,27.847500,27.860001,26.837500,27.332500,24.466448,212818400,-0.933450,0.000000,0.018842,0.019299,-0.018110,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2015-01-05,2015-01-05,27.072500,27.162500,26.352501,26.562500,23.777191,257142000,-0.949176,-0.028172,0.019200,0.022588,-0.007906,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2015-01-06,2015-01-06,26.635000,26.857500,26.157499,26.565001,23.779428,263188400,-0.949125,0.000094,0.002635,0.011011,-0.015340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2015-01-07,2015-01-07,26.799999,27.049999,26.674999,26.937500,24.112862,160423600,-0.941517,0.014022,-0.005104,0.004176,-0.009745,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2015-01-08,2015-01-08,27.307501,28.037500,27.174999,27.972500,25.039337,237458000,-0.920379,0.038422,-0.023773,0.002324,-0.028510,-0.032121,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900,1.201329,-0.002798,-0.007129,0.004247,-0.016836,0.007447,0.037760,0.053481,0.066745,0.080504,0.089390
2022-12-27,2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800,1.163954,-0.013878,0.010382,0.010613,-0.010075,0.018027,0.041244,0.059796,0.076302,0.089170,0.099680
2022-12-28,2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339417,85438400,1.082466,-0.030685,0.028800,0.039591,-0.001349,0.040321,0.058791,0.084423,0.104372,0.116677,0.128610
2022-12-29,2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700,1.155377,0.028324,-0.012499,0.006712,-0.014505,0.002654,0.019134,0.048726,0.066847,0.079571,0.092269
2022-12-30,2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207794,77034200,1.161912,0.002469,-0.011699,0.000154,-0.019241,-0.003356,0.011568,0.039616,0.057146,0.070404,0.084741

In [23]:
# category of sector (one hot encoding)
label = LabelEncoder()
label.fit(SP500_name["Sector"].unique())

for target in SP500_stock.keys():
    for label in SP500_name["Sector"].unique():
        cate = SP500_stock[target]["category"]
        if label != cate:
            SP500_stock[target]["stock_price"]["label_%s" % (label)] = 0
        if label == cate:
            SP500_stock[target]["stock_price"]["label_%s" % (label)] = 1
print('one hot sector over')

one hot sector over

In [24]:
len(SP500_name['Sector'].unique())

19

In [25]:
SP500_stock['AAPL']['stock_price']

,Date,Open,High,Low,Close,Adj Close,Volume,nor_close,return ratio,c_open,...,label_Producer Manufacturing,label_Commercial Services,label_Industrial Services,label_Utilities,label_Process Industries,label_Non-Energy Minerals,label_Transportation,label_Health Services,label_Energy Minerals,label_Communications
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,2015-01-02,27.847500,27.860001,26.837500,27.332500,24.466448,212818400,-0.933450,0.000000,0.018842,...,0,0,0,0,0,0,0,0,0,0
2015-01-05,2015-01-05,27.072500,27.162500,26.352501,26.562500,23.777191,257142000,-0.949176,-0.028172,0.019200,...,0,0,0,0,0,0,0,0,0,0
2015-01-06,2015-01-06,26.635000,26.857500,26.157499,26.565001,23.779428,263188400,-0.949125,0.000094,0.002635,...,0,0,0,0,0,0,0,0,0,0
2015-01-07,2015-01-07,26.799999,27.049999,26.674999,26.937500,24.112862,160423600,-0.941517,0.014022,-0.005104,...,0,0,0,0,0,0,0,0,0,0
2015-01-08,2015-01-08,27.307501,28.037500,27.174999,27.972500,25.039337,237458000,-0.920379,0.038422,-0.023773,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900,1.201329,-0.002798,-0.007129,...,0,0,0,0,0,0,0,0,0,0
2022-12-27,2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800,1.163954,-0.013878,0.010382,...,0,0,0,0,0,0,0,0,0,0
2022-12-28,2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339417,85438400,1.082466,-0.030685,0.028800,...,0,0,0,0,0,0,0,0,0,0
2022-12-29,2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700,1.155377,0.028324,-0.012499,...,0,0,0,0,0,0,0,0,0,0
2022-12-30,2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207794,77034200,1.161912,0.002469,-0.011699,...,0,0,0,0,0,0,0,0,0,0

In [26]:
# total feature
features = {}
for target in SP500_stock.keys():
    features[target] = SP500_stock[target]["stock_price"].iloc[30:, [4] + list(range(7, len(SP500_stock[target]["stock_price"].columns)))].reset_index(drop=True)
print('all features over')

all features over

In [27]:
features['AAPL']

,Close,nor_close,return ratio,c_open,c_high,c_low,5-days,10-days,15-days,20-days,...,label_Producer Manufacturing,label_Commercial Services,label_Industrial Services,label_Utilities,label_Process Industries,label_Non-Energy Minerals,label_Transportation,label_Health Services,label_Energy Minerals,label_Communications
0,31.957500,-0.838993,0.005902,-0.002660,0.008214,-0.007119,-0.017023,-0.041641,-0.059058,-0.076524,...,0,0,0,0,0,0,0,0,0,0
1,32.180000,-0.834449,0.006962,-0.008468,0.000466,-0.009866,-0.013409,-0.040444,-0.055423,-0.075140,...,0,0,0,0,0,0,0,0,0,0
2,32.112499,-0.835828,-0.002098,0.000234,0.004515,-0.000934,-0.005777,-0.031506,-0.046617,-0.065839,...,0,0,0,0,0,0,0,0,0,0
3,32.375000,-0.830467,0.008174,-0.006795,0.000000,-0.011197,-0.009143,-0.031977,-0.048891,-0.066811,...,0,0,0,0,0,0,0,0,0,0
4,33.250000,-0.812596,0.027027,-0.022406,0.000000,-0.025113,-0.026316,-0.046872,-0.065980,-0.083842,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1979,131.860001,1.201329,-0.002798,-0.007129,0.004247,-0.016836,0.007447,0.037760,0.053481,0.066745,...,0,0,0,0,0,0,0,0,0,0
1980,130.029999,1.163954,-0.013878,0.010382,0.010613,-0.010075,0.018027,0.041244,0.059796,0.076302,...,0,0,0,0,0,0,0,0,0,0
1981,126.040001,1.082466,-0.030685,0.028800,0.039591,-0.001349,0.040321,0.058791,0.084423,0.104372,...,0,0,0,0,0,0,0,0,0,0
1982,129.610001,1.155377,0.028324,-0.012499,0.006712,-0.014505,0.002654,0.019134,0.048726,0.066847,...,0,0,0,0,0,0,0,0,0,0
1983,129.929993,1.161912,0.002469,-0.011699,0.000154,-0.019241,-0.003356,0.011568,0.039616,0.057146,...,0,0,0,0,0,0,0,0,0,0

In [28]:
# movement of stock
Y_buy_or_not = {}
for target in SP500_stock.keys():
    Y_buy_or_not[target] = (features[target]["return ratio"] >= 0) * 1
    features[target]['buy_or_not'] = Y_buy_or_not[target]
print('movement label over')

movement label over

In [29]:
features['AAPL']

,Close,nor_close,return ratio,c_open,c_high,c_low,5-days,10-days,15-days,20-days,...,label_Commercial Services,label_Industrial Services,label_Utilities,label_Process Industries,label_Non-Energy Minerals,label_Transportation,label_Health Services,label_Energy Minerals,label_Communications,buy_or_not
0,31.957500,-0.838993,0.005902,-0.002660,0.008214,-0.007119,-0.017023,-0.041641,-0.059058,-0.076524,...,0,0,0,0,0,0,0,0,0,1
1,32.180000,-0.834449,0.006962,-0.008468,0.000466,-0.009866,-0.013409,-0.040444,-0.055423,-0.075140,...,0,0,0,0,0,0,0,0,0,1
2,32.112499,-0.835828,-0.002098,0.000234,0.004515,-0.000934,-0.005777,-0.031506,-0.046617,-0.065839,...,0,0,0,0,0,0,0,0,0,0
3,32.375000,-0.830467,0.008174,-0.006795,0.000000,-0.011197,-0.009143,-0.031977,-0.048891,-0.066811,...,0,0,0,0,0,0,0,0,0,1
4,33.250000,-0.812596,0.027027,-0.022406,0.000000,-0.025113,-0.026316,-0.046872,-0.065980,-0.083842,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1979,131.860001,1.201329,-0.002798,-0.007129,0.004247,-0.016836,0.007447,0.037760,0.053481,0.066745,...,0,0,0,0,0,0,0,0,0,0
1980,130.029999,1.163954,-0.013878,0.010382,0.010613,-0.010075,0.018027,0.041244,0.059796,0.076302,...,0,0,0,0,0,0,0,0,0,0
1981,126.040001,1.082466,-0.030685,0.028800,0.039591,-0.001349,0.040321,0.058791,0.084423,0.104372,...,0,0,0,0,0,0,0,0,0,0
1982,129.610001,1.155377,0.028324,-0.012499,0.006712,-0.014505,0.002654,0.019134,0.048726,0.066847,...,0,0,0,0,0,0,0,0,0,1
1983,129.929993,1.161912,0.002469,-0.011699,0.000154,-0.019241,-0.003356,0.011568,0.039616,0.057146,...,0,0,0,0,0,0,0,0,0,1

In [30]:
for target in SP500_stock.keys():
    print(target)

LVS
NWS
NWSA
LYV
DIS
ROL
CMG
MGM
CTAS
HLT
SBUX
CMCSA
DPZ
BKNG
YUM
MCD
MAR
DRI
EXPE
CZR
CHTR
WBD
RCL
CCL
WYNN
PARA
CRM
PANW
TYL
CSGP
NOW
VRSK
CDNS
IBM
SNPS
INTU
PTC
ADSK
PAYC
FICO
ANSS
ADBE
MSCI
NFLX
FTNT
ROP
TRMB
ORCL
EA
AKAM
BR
ATVI
META
FDS
MSFT
JKHY
ADP
VRSN
IT
FFIV
PAYX
MTCH
GOOG
ACN
GOOGL
EPAM
CDW
J
JNPR
CSCO
CTSH
GEN
FIS
TTWO
TAP
CLX
VFC
TSN
EL
CHD
MNST
BF-B
CL
MKC
NKE
PEP
KDP
KMB
PG
KO
HSY
K
MDLZ
HRL
CAG
PM
CPB
GIS
RL
MO
STZ
IFF
SJM
WELL
VTR
DLR
EQIX
AMT
CPT
SBAC
PGR
IRM
AJG
O
ICE
MKTX
ARE
WY
PLD
KIM
CBRE
PRU
FI
EQR
MMC
ESS
UDR
REG
MAA
BRO
CCI
AON
CME
CBOE
MET
NDAQ
AIZ
PEAK
EXR
FRT
AVB
WTW
BLK
SPG
SCHW
TRV
BEN
AXP
TROW
AMP
HST
BXP
MS
CB
GS
NTRS
URI
WRB
RJF
GL
BK
ACGL
CINF
PSA
PFG
L
EG
HIG
IVZ
WFC
USB
AFL
AIG
JPM
STT
BRK-B
PNC
BAC
RF
COF
MTB
FITB
KEY
HBAN
C
TFC
DFS
CFG
SYF
ZION
CMA
ALL
PODD
CTLT
STE
DXCM
MRK
ALGN
LLY
ISRG
COO
WST
IDXX
ZBH
BDX
TECH
INCY
SYK
ZTS
HOLX
TMO
ABT
JNJ
EW
A
ABBV
MTD
DHR
MDT
TFX
RMD
VRTX
WAT
REGN
AMGN
RVTY
GILD
BMY
BIIB
PFE
VTRS
ILMN
WBA
BAX
BIO
XRAY
NVDA
AXON
FSLR
MPWR
TDG
GLW
LHX
ANET
ENPH
MSI
TER
AAPL
APH
AVGO
TDY
ADI
ROK
HON
RTX
ZBRA
ON
KEYS
TXN
KLAC
TEL
GRMN
LDOS
NXPI
GD
MCHP
TXT
HII
LMT
SWKS
QCOM
NOC
NTAP
HPQ
AMD
INTC
BA
MU
EMR
STX
WDC
QRVO
AMZN
COST
WMT
CVS
KMX
TJX
ORLY
ROST
DLTR
TSCO
LOW
HD
AZO
ULTA
TGT
EBAY
DG
KR
BBY
BBWI
AAP
TPR
CAH
BSX
FAST
POOL
HSIC
COR
GWW
GPC
MCK
TSLA
SWK
SNA
LKQ
NVR
F
DHI
LEN
PHM
GM
HAS
WHR
XYL
GNRC
AOS
ETN
WAB
APTV
AME
IEX
NDSN
PH
TT
ITW
PNR
JCI
LRCX
DOV
AMAT
ALLE
CAT
MAS
GE
CMI
PCAR
DE
BWA
MMM
SPGI
EFX
MCO
GPN
MA
CPRT
V
FLT
CRL
RHI
IPG
OMC
PWR
BKR
RSG
WM
SLB
WMB
KMI
HAL
OKE
DUK
FE
AWK
EIX
PPL
CNP
SO
TRGP
CMS
PNW
AEP
WEC
ATO
LNT
ES
AEE
EXC
XEL
NI
PCG
D
SRE
EVRG
NEE
DTE
ETR
ED
PEG
AES
NRG
ECL
LIN
SHW
APD
AVY
PPG
BALL
FMC
PKG
LYB
EMN
AMCR
SEE
ADM
CE
BG
IP
DD
CF
MOS
ALB
VMC
MLM
FCX
NUE
STLD
NEM
LUV
ALK
ODFL
JBHT
CHRW
SYY
UNP
NSC
EXPD
FDX
CSX
UPS
DAL
UAL
AAL
IQV
LH
UNH
DVA
MOH
DGX
HUM
ELV
UHS
HCA
CNC
CI
HES
COP
OXY
CVX
PXD
APA
EOG
XOM
MRO
FANG
CTRA
DVN
MPC
PSX
EQT
VLO
TMUS
VZ
T

In [31]:
## Trianing & Testing ##
train_size = 0.8
test_size = 0.2
days = len(features["AAPL"])

train_day = int(days * train_size)

# data of training set and testing set
train_data = {}
test_data = {}

train_Y_buy_or_not = {}
test_Y_buy_or_not = {}

train_return_ratio = {}
test_return_ratio = {}

for i in SP500_stock.keys():
    train_data[i] = features[i].drop(['return ratio','buy_or_not'], axis=1).iloc[:train_day, :]
    train_Y_buy_or_not[i] = features[i]['buy_or_not'][:train_day]
    train_return_ratio[i] = features[i]['return ratio'][:train_day]
    
    test_data[i] = features[i].drop(['return ratio','buy_or_not'], axis=1).iloc[train_day:, :]
    test_Y_buy_or_not[i] = features[i]['buy_or_not'][train_day:]
    test_return_ratio[i] = features[i]['return ratio'][train_day:]
print('train&test over')

train&test over

In [32]:
train_data['AAPL']

,Close,nor_close,c_open,c_high,c_low,5-days,10-days,15-days,20-days,25-days,...,label_Producer Manufacturing,label_Commercial Services,label_Industrial Services,label_Utilities,label_Process Industries,label_Non-Energy Minerals,label_Transportation,label_Health Services,label_Energy Minerals,label_Communications
0,31.957500,-0.838993,-0.002660,0.008214,-0.007119,-0.017023,-0.041641,-0.059058,-0.076524,-0.091594,...,0,0,0,0,0,0,0,0,0,0
1,32.180000,-0.834449,-0.008468,0.000466,-0.009866,-0.013409,-0.040444,-0.055423,-0.075140,-0.091824,...,0,0,0,0,0,0,0,0,0,0
2,32.112499,-0.835828,0.000234,0.004515,-0.000934,-0.005777,-0.031506,-0.046617,-0.065839,-0.084238,...,0,0,0,0,0,0,0,0,0,0
3,32.375000,-0.830467,-0.006795,0.000000,-0.011197,-0.009143,-0.031977,-0.048891,-0.066811,-0.085578,...,0,0,0,0,0,0,0,0,0,0
4,33.250000,-0.812596,-0.022406,0.000000,-0.025113,-0.026316,-0.046872,-0.065980,-0.083842,-0.101768,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,124.610001,1.053261,0.007704,0.009550,-0.000481,0.012343,0.010585,0.009678,0.017446,0.028267,...,0,0,0,0,0,0,0,0,0,0
1583,124.279999,1.046521,0.006437,0.008610,-0.002736,0.010492,0.011667,0.010981,0.016825,0.027638,...,0,0,0,0,0,0,0,0,0,0
1584,125.059998,1.062451,-0.006237,0.001439,-0.008076,0.001247,0.005525,0.004222,0.009368,0.018244,...,0,0,0,0,0,0,0,0,0,0
1585,123.540001,1.031408,0.009228,0.010604,-0.003319,0.008208,0.016966,0.016993,0.019941,0.027521,...,0,0,0,0,0,0,0,0,0,0
1586,125.889999,1.079403,-0.014457,0.002145,-0.016205,-0.009643,-0.003146,-0.001504,-0.000628,0.005929,...,0,0,0,0,0,0,0,0,0,0

In [33]:
week = 4

In [34]:
# week represents the number of our inputs
def before_day(week):
    # train
    train = {}
    for w in range(week):
        train_x = []
        for tr_ind in range(len(train_data["AAPL"]) - 7 - (week - 2) - 1):
            tr = []
            valid_train = True  # 假设数据是有效的
            for target in SP500_stock.keys():
                data = train_data[target]
                slice_train = data.iloc[tr_ind + w: tr_ind + w + 7, :].values

                # 检查数据形状是否为 (7, 30)
                if slice_train.shape != (7, 30):
                    valid_train = False
                    break  # 如果数据形状不正确，跳出循环

                tr.append(slice_train)

            if valid_train:
                train_x.append(tr)
        train["x%s" % (w + 1)] = np.array(train_x)
    print('train_x over')

    train_y1, train_y2 = [], []
    for tr_ind in range(len(train_data["AAPL"]) - 7 - (week - 2) - 1):
        all_stock_name = list(SP500_stock.keys())
        tr_y1, tr_y2 = [], []
        for target in SP500_stock.keys():
            data = train_data[target]
            tr_y1.append(train_return_ratio[target].iloc[tr_ind + (week - 1) + 7])
            tr_y2.append(train_Y_buy_or_not[target].iloc[tr_ind + (week - 1) + 7])
        train_y1.append(tr_y1)
        train_y2.append(tr_y2)
    train["y_return ratio"] = np.array(train_y1)
    train["y_up_or_down"] = np.array(train_y2)
    print('train_y over')
    print(train["y_return ratio"].shape)

    # test
    test = {}
    for w in range(week):
        test_x = []
        for te_ind in range(len(test_data["AAPL"]) - 7 - (week - 2) - 1):
            te = []
            valid_test = True  # 假设数据是有效的
            for target in SP500_stock.keys():
                data = test_data[target]
                slice_test = data.iloc[te_ind + w: te_ind + w + 7, :].values
                # 检查数据形状是否为 (7, 30)
                if slice_test.shape != (7, 30):
                    valid_test = False
                    break  # 如果数据形状不正确，跳出循环
                te.append(slice_test)
            if valid_test:
                test_x.append(te)
        test["x%s" % (w + 1)] = np.array(test_x)
    print('test_x over')

    test_y1, test_y2 = [], []
    for te_ind in range(len(test_data["AAPL"]) - 7 - (week - 2) - 1):
        te_y1, te_y2 = [], []
        for target in SP500_stock.keys():
            data = test_data[target]
            te_y1.append(test_return_ratio[target].iloc[te_ind + (week - 1) + 7])
            te_y2.append(test_Y_buy_or_not[target].iloc[te_ind + (week - 1) + 7])
        test_y1.append(te_y1)
        test_y2.append(te_y2)
    test["y_return ratio"] = np.array(test_y1)
    test["y_up_or_down"] = np.array(test_y2)
    print('test_y over')
    print(test["y_return ratio"].shape)
    data = {"train": train, "test": test}

    return data

In [35]:
data = before_day(4)

train_x over
train_y over
(1577, 475)
test_x over
test_y over
(387, 475)

In [36]:
data['train']['x2'].shape

(1577, 475, 7, 30)

In [37]:
data['train']['y_return ratio'].shape

(1577, 475)

In [38]:
with open("./datasets4/sp500_data.pkl", "wb") as f:
    pickle.dump(data, f)
f.close()